[package]
name = "alloy-parser"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# A byte-oriented, zero-copy, parser combinators library
nom = "7.1.1"

